server:
  name: Apache HTTP Server
  version: 2.4.41
  port: 80
  document_root: /var/www/html
  error_log: /var/log/httpd/error.log
  access_log: /var/log/httpd/access.log
  server_admin: webmaster@example.com
  server_name: example.com
  server_alias: www.example.com

application:
  name: Hello World Application
  description: Uma simples aplicação Hello World
  files_location: /var/www/html/hello_world
  index_file: index.html
